DATASET:
  PREPROCESSING:
    DOWNSCALE_FACTOR: 2
    NORMALIZE_LR:
      THRESHOLD: 3.949552855076219e-06
      MEAN: 1.7622385777225147
      STD: 0.35664469842091917
    NORMALIZE_LR_DN:
      THRESHOLD: 6.884854889849852e-06
      MEAN: 2.387432245819528 
      STD: 0.22396113768555362
    NORMALIZE_HR:
      THRESHOLD: 3.949552855076219e-06
      MEAN: 1.4221355768782358
      STD: 0.36985040461144786
    NORMALIZE_HR_DN:
      THRESHOLD: 6.884854889849852e-06
      MEAN: 1.783816491222639 
      STD: 0.22528552769578153
  IMAGE_SIZE: 256
  IN_CHANNELS: 1
  NUM_THREADS: 0
  BATCH_SIZE: 1

TRAIN:
  PATH_TO_SAVE: './train/train_results'
  PATH_TO_LR: './train/slc_lr'
  PATH_TO_HR: './train/denoised_hr'
  PATH_TO_WEIGHTS: './weights' #None if no path
  EPOCH: 10
  CHECKPOINT_STEP: 5
  BATCH_SIZE: 1
  VALID_RATIO: 0.2
  SUMMARY: False
  LOSS :
    NAME: "huber"
  OPTIMIZER:
    NAME: Adam
    ADAM:
      WEIGHT_DECAY: 0
      LR_INITIAL: 0.001
  SCHEDULER:
    NAME: "ReduceOnPlateau"
    ReduceOnPlateau:
      PATIENCE: 10
      THRESH: 0.0001
  
INFERENCE:
  PATH_TO_SAVE: './data/results'
  PATH_TO_SLC: './data/slc_lr'
  PATH_TO_DENOISED: './data/denoised_lr'
  PATH_TO_WEIGHTS: './weights'
  BATCH_SIZE: 1
  STRIDE: 32
  SAVE_ARRAY: True
  SAVE_PNG: True

MODEL:
  SRCNN:
    BASE_CHANNELS: 32
  SRCNN2:
    BASE_CHANNELS: 64
    DEPTH: 3
  SWINTRANSFORMER:
    IN_CHANNELS: 1
    WINDOW_SIZE: 8
    IMG_SIZE: 64
    IMG_RANGE: 1
    DEPTHS : [4, 4, 4]
    EMBED_DIM: 60
    NUM_HEADS: [4, 4, 4]
    MLP_RATIO: 2
    UPSAMPLER: "pixelshuffledirect"
    RESI_CONNECTION: "1conv"
